Option Explicit

' Dashboard
Global Const CurrentYear = "B5"
Global Const GL_Symbol_C = "R"
Global Const GL_Method_C = "S"
Global Const GL_Method_FirstRow = 6

' Trading Tab
Global Const TR_Year = "A"
Global Const TR_Date = "B"
Global Const TR_Action = "C"
Global Const TR_Symbol = "D"
Global Const TR_Account = "E"
Global Const TR_Volume = "F"
Global Const TR_Price = "G"
Global Const TR_Currency = "H"
Global Const TR_Fee = "I"
Global Const TR_FeeCurrency = "J"
Global Const TR_Total = "K"
Global Const TR_CostProceeds = "L"
Global Const TR_ExchangeId = "M"
Global Const TR_Memo = "N"
Global Const TR_USDTotalCost = "O"
Global Const TR_USDFeeCost = "P"
Global Const TR_TXID = "Q"

' Spending Tab
Global Const SP_Year = "A"
Global Const SP_Date = "B"
Global Const SP_Action = "C"
Global Const SP_Symbol = "D"
Global Const SP_Account = "E"
Global Const SP_Volume = "F"
Global Const SP_Price = "G"
Global Const SP_Currency = "H"
Global Const SP_Fee = "I"
Global Const SP_FeeCurrency = "J"
Global Const SP_Total = "K"
Global Const SP_Memo = "L"
Global Const SP_Recipient = "M"
Global Const SP_USDTotalCost = "N"
Global Const SP_TXID = "O"

' Income Tab
Global Const INC_Year = "A"
Global Const INC_Date = "B"
Global Const INC_Action = "C"
Global Const INC_Symbol = "D"
Global Const INC_Account = "E"
Global Const INC_Volume = "F"
Global Const INC_Price = "G"
Global Const INC_Currency = "H"
Global Const INC_Fee = "I"
Global Const INC_FeeCurrency = "J"
Global Const INC_Total = "K"
Global Const INC_Memo = "L"
Global Const INC_Recipient = "M"
Global Const INC_USDTotalCost = "N"
Global Const INC_TXID = "O"

' UTXOs Tab
Global Const UTXO_Symbol = "A"
Global Const UTXO_Year = "B"
Global Const UTXO_DateAcquired = "C"
Global Const UTXO_Volume = "D"
Global Const UTXO_PriceUSD = "E"
Global Const UTXO_CostBasisUSD = "F"
Global Const UTXO_CostBasisOpenUSD = "G"
Global Const UTXO_CostBasisVolumeOpen = "H"
Global Const UTXO_Category = "I"
Global Const UTXO_TXID = "J"
Global Const UTXO_CB_Change = "K"
Global Const UTXO_CB_Vol_Change = "L"
Global Const UTXO_CB_Vol_Open = "M"
Global Const UTXO_LiqTXIDs = "N"

' Events Tab
Global Const EVT_Date = "A"
Global Const EVT_Action = "B"
Global Const EVT_Symbol = "C"
Global Const EVT_Volume = "D"
Global Const EVT_PriceUSD = "E"
Global Const EVT_TXID = "F"

'Liquidation
Global Const LIQ_Year = "A"
Global Const LIQ_Symbol = "B"
Global Const LIQ_Action = "C"
Global Const LIQ_DateAcquired = "D"
Global Const LIQ_DateSold = "E"
Global Const LIQ_Volume = "F"
Global Const LIQ_Proceeds = "G"
Global Const LIQ_CostBasis = "H"
Global Const LIQ_Gain = "I"
Global Const LIQ_Currency = "J"
Global Const LIQ_TXID = "K"
Global Const LIQ_UTXO_TXID = "L"
Global Const LIQ_Unmatched = "M"
